### ISSUE TITLE
Inject not wiring

### ISSUE THREAD

**Issue by vimtor** [Finistere/antidote#29] opened 2021-03-04 15:18 UTC
The following code, partially extracted from the docs:

```python3
from antidote import implementation, Service, inject

class Database:
    pass

class PostgresDB(Service, Database):
    def __repr__(self):
        return 'Postgres'

class MySQLDB(Service, Database):
    def __repr__(self):
        return 'MySQL'

@implementation(Database, permanent=True)
def choose_db():
    return PostgresDB

@inject
def print_db(db: Database):
    print(db)

print_db()
```

Throws the following error:

![image](https://user-images.githubusercontent.com/36263538/109984652-45d72180-7d04-11eb-90a9-d6c393ccf65e.png)

**Comment by Finistere** [comment] 2021-03-04 16:56
Hello ! It's not a bug, it's a feature. :D 

Had it worked, you would have no way of knowing where the `Database` is coming from when using `print_db()`. So Antidote forces you to be more explicit by forcing you to specify from where the dependency is actually coming from. Example:

```python
@inject([Database @ choose_db])
def print_db(db: Database):
    print(db)
```

Or with type hint annotations:

```python
from antidote import From
from typing import Annotated

@inject
def print_db(db: Annotated[Database, From(choose_db)]):
    print(db)
```

If you use it often, you could also use a type alias:

```python
MyDatabase = Annotated[Database, From(choose_db)]

@inject
def print_db(db: MyDatabase):
    print(db)
```

Hope that helps ! If not, happy to provide more help.

Could you please tell me how you came up with your example ? I'd love to know which parts of the documentation / readme need to be improved or are missing. Or if you simply didn't read a section because it was too long, simple or complex. :)

**Comment by Finistere** [comment] 2021-03-04 21:06
Oh I see now the issue with the documentation. Indeed the "How to / Use interface" is wrong. I'm surprised it passes the doctests, I probably mixed things.

**Comment by Finistere** [comment] 2021-03-04 21:41
Fixed they were two issues:
- stable documented seems to have stopped updating at v0.10 for an unknown reason.
- the [interface recipe](https://antidote.readthedocs.io/en/latest/recipes.html#use-interfaces) in the documentation did need some refresh.

Let me know if this wasn't the source of your issue !

**Comment by Finistere** [comment] 2021-03-12 19:24
Closing, the issue is fixed.

**Closed by Finistere** 2021-03-12 19:24 UTC
